### ISSUE TITLE
dttv apk在高版本android上拿不到storage的权限

### ISSUE THREAD

**Issue by peterfuture** [peterfuture/dttv-android#20]
java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/video/media from pid=7975, uid=10188 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:639)
at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java :501)
at android.content.ContentProvider$Transport.query(ContentProvider.java:213)
at android.content.ContentProviderNative.onTransact(ContentProviderNative.java: 102)
at android.os.Binder.execTransact(Binder.java:700)
09-04 15:40:48.914 7975-7975/dttv.app E/AndroidRuntime: FATAL EXCEPTION: main
Process: dttv.app, PID: 7975
java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/video/media from pid=7975, uid=10188 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
at android.os.Parcel.readException(Parcel.java:2004)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java: 183)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java: 135)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:418) at android.content.ContentResolver.query(ContentResolver.java:756)
at android.content.ContentResolver.query(ContentResolver.java:705)
at android.content.ContentResolver.query(ContentResolver.java:663)
at dttv.app.frament.LocalVideoFragment.initVideos(LocalVideoFragment.java:66)
at dttv.app.frament.LocalVideoFragment.initEventAndData(LocalVideoFragment.java: 50)
at dttv.app.base.SimpleFragment.onViewCreated(SimpleFragment.java:50)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java: 1432)
at 
android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Fragment Manager.java:1752)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java: 1821)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java: 797)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2595)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.ja va:2382)
at
 android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute( FragmentManager.java:2337)
at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java: 2214)
at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecor d.java:649)
at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java: 145)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
at android.view.View.measure(View.java:22097)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715) at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
at android.view.View.measure(View.java:22097)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6604)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at
android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java: 141)
at android.view.View.measure(View.java:22097)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6604) at
android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.ja va:400)
at android.view.View.measure(View.java:22097)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6604)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at android.view.View.measure(View.java:22097)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6604)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514) at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
at android.view.View.measure(View.java:22097)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6604)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:727)
at android.view.View.measure(View.java:22097)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2450)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1532)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1789)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1420)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6807)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:968)
at android.view.Choreographer.doCallbacks(Choreographer.java:780)
at android.view.Choreographer.doFrame(Choreographer.java:715)

at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6600) at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java: 518)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

**Comment by peterfuture** [comment]
fixed
https://github.com/peterfuture/dttv-android/commit/c3aed14cb7dd861514cc867115199e1dfd55ac53
