### ISSUE TITLE
启动apk出现闪退

### ISSUE THREAD

**Issue by peterfuture** [peterfuture/dttv-android#7]
启动apk出现闪退， 详细log如下

D/AndroidRuntime( 5227): 
D/AndroidRuntime( 5227): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 5227): CheckJNI is ON
D/dalvikvm( 5227): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 5227): Added shared lib libjavacore.so 0x0
D/dalvikvm( 5227): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 5227): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 5227): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
E/cutils-trace( 5227): Error opening trace file: No such file or directory (2)
D/dalvikvm( 5227): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/memtrack( 5227): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 5227): failed to load memtrack module: -2
I/ethernet( 5227): Loading ethernet jni class
I/pppoe   ( 5227): Loading pppoe jni class
D/AndroidRuntime( 5227): Calling main entry com.android.commands.pm.Pm
D/AndroidRuntime( 5227): Shutting down VM
D/jdwp    ( 5227): Got wake-up signal, bailing out of select
D/dalvikvm( 5227): Debugger has detached; object registry had 1 entries
D/AndroidRuntime( 5238): 
D/AndroidRuntime( 5238): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 5238): CheckJNI is ON
D/dalvikvm( 5238): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 5238): Added shared lib libjavacore.so 0x0
D/dalvikvm( 5238): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 5238): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 5238): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
E/cutils-trace( 5238): Error opening trace file: No such file or directory (2)
D/dalvikvm( 5238): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/memtrack( 5238): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 5238): failed to load memtrack module: -2
I/ethernet( 5238): Loading ethernet jni class
I/pppoe   ( 5238): Loading pppoe jni class
D/AndroidRuntime( 5238): Calling main entry com.android.commands.am.Am
--------- beginning of /dev/log/system
I/ActivityManager(  524): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=dttv.app/.MainActivity} from pid 5238
I/ActivityManager(  524): start package name is dttv.app, class name is dttv.app.MainActivity, error code is 0
D/dalvikvm(  524): GC_FOR_ALLOC freed 1329K, 28% free 7166K/9896K, paused 39ms, total 40ms
D/MediaBoxLauncher( 1427): ------onPause
D/AndroidRuntime( 5238): Shutting down VM
D/jdwp    ( 5238): Got wake-up signal, bailing out of select
D/dalvikvm( 5238): Debugger has detached; object registry had 1 entries
D/dalvikvm( 5249): Not late-enabling CheckJNI (already on)
I/ActivityManager(  524): Start proc dttv.app for activity dttv.app/.MainActivity: pid=5249 uid=10068 gids={50068, 1028, 1015}
D/dalvikvm( 5249): GC_FOR_ALLOC freed 246K, 26% free 788K/1060K, paused 4ms, total 4ms
D/dalvikvm( 5249): GC_FOR_ALLOC freed 276K, 24% free 1021K/1328K, paused 5ms, total 5ms
D/TextLayoutCache( 5249): Using debug level = 0 - Debug Enabled = 0
D/dalvikvm( 5249): GC_FOR_ALLOC freed 126K, 11% free 1382K/1540K, paused 6ms, total 6ms
D/dalvikvm( 5249): GC_FOR_ALLOC freed 6K, 11% free 1431K/1596K, paused 6ms, total 6ms
I/dalvikvm-heap( 5249): Grow heap (frag case) to 2.028MB for 635812-byte allocation
D/dalvikvm( 5249): GC_FOR_ALLOC freed <1K, 8% free 2052K/2220K, paused 11ms, total 11ms
D/AudioUIFragment( 5249): scanFile
I/FilesUIFragment( 5249): enter onCreateView this.getId() is:2131034188
I/FilesUIFragment( 5249): enter onActivityCreated
W/linker  ( 5249): libamffmpeg.so has text relocations. This is wasting memory and is a security risk. Please fix.
I/dalvikvm( 5249): threadid=1: recursive native library load attempt (/system/lib/libmedia_jni.so)
D/MtpDeviceJNI( 5249): register_android_mtp_MtpDevice
I/dalvikvm( 5249): threadid=1: recursive native library load attempt (/system/lib/libmedia_jni.so)
I/dalvikvm( 5249): threadid=1: recursive native library load attempt (/system/lib/libmedia_jni.so)
I/dalvikvm( 5249): threadid=1: recursive native library load attempt (/system/lib/libmedia_jni.so)
I/FilesUIFragment( 5249): enter onResume
D/libEGL  ( 5249): loaded /system/lib/egl/libGLES_mali.so
D/OpenGLRenderer( 5249): Enabling debug mode 0
D/AndroidRuntime( 5249): Shutting down VM
W/dalvikvm( 5249): threadid=1: thread exiting with uncaught exception (group=0x416b0ba8)
E/AndroidRuntime( 5249): FATAL EXCEPTION: main
E/AndroidRuntime( 5249): Process: dttv.app, PID: 5249
E/AndroidRuntime( 5249): java.lang.NullPointerException
E/AndroidRuntime( 5249):    at android.widget.TabWidget.onFocusChange(TabWidget.java:524)
E/AndroidRuntime( 5249):    at android.view.View.onFocusChanged(View.java:4836)
E/AndroidRuntime( 5249):    at android.widget.TextView.onFocusChanged(TextView.java:7641)
E/AndroidRuntime( 5249):    at android.view.View.handleFocusGainInternal(View.java:4617)
E/AndroidRuntime( 5249):    at android.view.View.requestFocusNoSearch(View.java:6999)
E/AndroidRuntime( 5249):    at android.view.View.requestFocus(View.java:6978)
E/AndroidRuntime( 5249):    at android.view.View.requestFocus(View.java:6945)
E/AndroidRuntime( 5249):    at android.view.View.requestFocus(View.java:6924)
E/AndroidRuntime( 5249):    at android.widget.TabWidget.onFocusChange(TabWidget.java:514)
E/AndroidRuntime( 5249):    at android.view.View.onFocusChanged(View.java:4836)
E/AndroidRuntime( 5249):    at android.view.View.handleFocusGainInternal(View.java:4617)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.handleFocusGainInternal(ViewGroup.java:604)
E/AndroidRuntime( 5249):    at android.view.View.requestFocusNoSearch(View.java:6999)
E/AndroidRuntime( 5249):    at android.view.View.requestFocus(View.java:6978)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2369)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2414)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2370)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2414)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2370)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2414)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2370)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2414)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2370)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2414)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2370)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2414)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2370)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2414)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2370)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2414)
E/AndroidRuntime( 5249):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2373)
E/AndroidRuntime( 5249):    at android.view.View.requestFocus(View.java:6945)
E/AndroidRuntime( 5249):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1830)
E/AndroidRuntime( 5249):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
E/AndroidRuntime( 5249):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5672)
E/AndroidRuntime( 5249):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:772)
E/AndroidRuntime( 5249):    at android.view.Choreographer.doCallbacks(Choreographer.java:585)
E/AndroidRuntime( 5249):    at android.view.Choreographer.doFrame(Choreographer.java:555)
E/AndroidRuntime( 5249):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:758)
E/AndroidRuntime( 5249):    at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 5249):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 5249):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 5249):    at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 5249):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5249):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 5249):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
E/AndroidRuntime( 5249):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
E/AndroidRuntime( 5249):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  524):   Force finishing activity dttv.app/.MainActivity
I/WindowManager(  524): Screenshot max retries 4 of Token{41c54cb8 ActivityRecord{41c54b58 u0 dttv.app/.MainActivity t17 f}} appWin=Window{419acf38 u0 Starting dttv.app} drawState=4
W/WindowManager(  524): Screenshot failure taking screenshot for (1920x1080) to layer 21015
I/Process ( 5249): Sending signal. PID: 5249 SIG: 9
I/ActivityManager(  524): Process dttv.app (pid 5249) has died.
I/WindowState(  524): WIN DEATH: Window{41a42f28 u0 dttv.app/dttv.app.MainActivity}
W/ContextImpl(  524): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1162 com.android.server.am.ActivityManagerService.onVideoPlayerCrashed:3689 com.android.server.am.ActivityManagerService.handleAppDiedLocked:3719 com.android.server.am.ActivityManagerService.appDiedLocked:3857 com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied:1046 
D/ActivityManager(  524): send app_CRASH broadcast, packageName:dttv.app
W/InputMethodManagerService(  524): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41b2b388 attribute=null, token = android.os.BinderProxy@41b45d78
W/WindowManager(  524): Rebuild removed 2 windows but added 1
W/WindowManager(  524): java.lang.RuntimeException: here
W/WindowManager(  524):     at com.android.server.wm.WindowManagerService.rebuildAppWindowListLocked(WindowManagerService.java:8188)
W/WindowManager(  524):     at com.android.server.wm.WindowManagerService.rebuildAppWindowListLocked(WindowManagerService.java:8124)
W/WindowManager(  524):     at com.android.server.wm.WindowManagerService.handleAnimatingStoppedAndTransitionLocked(WindowManagerService.java:8868)
W/WindowManager(  524):     at com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedInner(WindowManagerService.java:9382)
W/WindowManager(  524):     at com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedLoop(WindowManagerService.java:8340)
W/WindowManager(  524):     at com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLocked(WindowManagerService.java:8282)
W/WindowManager(  524):     at com.android.server.wm.WindowManagerService.access$400(WindowManagerService.java:159)
W/WindowManager(  524):     at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:7274)
W/WindowManager(  524):     at android.os.Handler.dispatchMessage(Handler.java:102)
W/WindowManager(  524):     at android.os.Looper.loop(Looper.java:136)
W/WindowManager(  524):     at android.os.HandlerThread.run(HandlerThread.java:61)
W/WindowManager(  524): This window was lost: Window{41a42f28 u0 dttv.app/dttv.app.MainActivity EXITING}
W/WindowManager(  524): mDisplayId=0 mSession=Session{41b716e0 5249:u0a10068} mClient=android.os.BinderProxy@41b6bae0
W/WindowManager(  524): mOwnerUid=10068 mShowToOwnerOnly=true package=dttv.app appop=NONE
W/WindowManager(  524): mAttrs=WM.LayoutParams{(0,0)(fillxfill) sim=#110 ty=1 fl=#1810100 pfl=0x8 wanim=0x10302a1}
W/WindowManager(  524): Requested w=1920 h=1080 mLayoutSeq=621
W/WindowManager(  524): mBaseLayer=21000 mSubLayer=0 mAnimLayer=21005+0=21005 mLastLayer=21010
W/WindowManager(  524): mToken=AppWindowToken{41fdb688 token=Token{41c54cb8 ActivityRecord{41c54b58 u0 dttv.app/.MainActivity t17}}}
W/WindowManager(  524): mRootToken=AppWindowToken{41fdb688 token=Token{41c54cb8 ActivityRecord{41c54b58 u0 dttv.app/.MainActivity t17}}}
W/WindowManager(  524): mAppToken=AppWindowToken{41fdb688 token=Token{41c54cb8 ActivityRecord{41c54b58 u0 dttv.app/.MainActivity t17}}}
W/WindowManager(  524): mViewVisibility=0x0 mHaveFrame=true mObscured=true
W/WindowManager(  524): mSeq=0 mSystemUiVisibility=0x0
W/WindowManager(  524): mGivenContentInsets=[0,0][0,0] mGivenVisibleInsets=[0,0][0,0]
W/WindowManager(  524): mConfiguration={1.0 ?mcc?mnc en_US ldltr sw720dp w1280dp h694dp 240dpi xlrg long land television -touch -keyb/v/h dpad/v s.5}
W/WindowManager(  524): mHasSurface=true mShownFrame=[0.0,0.0][1920.0,1080.0] isReadyForDisplay()=false
W/WindowManager(  524): mFrame=[0,0][1920,1080] last=[0,0][1920,1080]
W/WindowManager(  524): mSystemDecorRect=[0,38][1920,1080] last=[0,38][1920,1080]
W/WindowManager(  524): Frames: containing=[0,0][1920,1080] parent=[0,0][1920,1080]
W/WindowManager(  524):     display=[0,0][1920,1080] overscan=[0,0][1920,1080]
W/WindowManager(  524):     content=[0,38][1920,1080] visible=[0,38][1920,1080]
W/WindowManager(  524):     decor=[0,38][1920,1080]
W/WindowManager(  524): Cur insets: overscan=[0,0][0,0] content=[0,38][0,0] visible=[0,38][0,0]
W/WindowManager(  524): Lst insets: overscan=[0,0][0,0] content=[0,38][0,0] visible=[0,38][0,0]
W/WindowManager(  524): WindowStateAnimator{41fb5650 dttv.app/dttv.app.MainActivity}:
W/WindowManager(  524):   mSurface=Surface(name=dttv.app/dttv.app.MainActivity)
W/WindowManager(  524):   mDrawState=DRAW_PENDING mLastHidden=true
W/WindowManager(  524):   Surface: shown=false layer=21010 alpha=1.0 rect=(0.0,0.0) 1920.0 x 1080.0
W/WindowManager(  524): mExiting=true mRemoveOnExit=true mDestroying=false mRemoved=false
W/WindowManager(  524): Current app token list:
V/WindowManager(  524):   Display 0

W/WindowManager(  524): Final window list:
V/WindowManager(  524):   #0: Window{418b9e40 u0 SearchPanel}
V/WindowManager(  524):   #1: Window{419ddc58 u0 NavigationBar}
V/WindowManager(  524):   #2: Window{41a078e0 u0 StatusBar}
V/WindowManager(  524):   #3: Window{418f3718 u0 KeyguardScrim}
V/WindowManager(  524):   #4: Window{41b45ff0 u0 
V/WindowManager(  524):   #5: Window{419e7068 u0 com.android.systemui.ImageWallpaper}

**Comment by peterfuture** [comment]
Have been fixed in latest Version
